sherpa_rover:
    collision_wheel_joint_bl_position_controller:
        type: effort_controllers/JointPositionController
        joint: collision_wheel_joint_bl
        pid: {p: 100.0, i: 0.01, d: 10.0}
    collision_wheel_joint_br_position_controller:
        type: effort_controllers/JointPositionController
        joint: collision_wheel_joint_br
        pid: {p: 100.0, i: 0.01, d: 10.0}
    collision_wheel_joint_fl_position_controller:
        type: effort_controllers/JointPositionController
        joint: collision_wheel_joint_fl
        pid: {p: 100.0, i: 0.01, d: 10.0}
    collision_wheel_joint_fr_position_controller:
        type: effort_controllers/JointPositionController
        joint: collision_wheel_joint_fr
        pid: {p: 100.0, i: 0.01, d: 10.0}